### ISSUE TITLE
[BUG] It is not clear what the "Add connection" button does

### ISSUE THREAD

**Issue by lourkeur** [dedis/popstellar#1118]
### Description (Actual behavior)
In FE1, under "Add connection", the qrcode scanner complains that the connection code is for a different LAO. With a code from the same LAO it works, but that's moot.
![image](https://user-images.githubusercontent.com/15657735/173611285-9bfdfb09-98e3-40b3-8698-1b320226aa50.png)

### Expected behavior
~~The whole point of this screen seems to be to go to a different LAO so it should accept those qrcode.~~

Correct behaviour but apparently not what the user is expecting.

### How to reproduce
1. Go to `(i)` in the home screen
2. Click on 'Add connection'
3. Present a qr code
4. See error in an orange toast

### Version & Environment
This bug was reproduced on:
- Commit: 0573381504

##### Front-ends:
- [x] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

##### Environment (as applicable):
 - Device: DH67CL Desktop Computer
 - OS: Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.20220612.1f8d880
 - Browser: Firefox 101.0.1

### Workaround
Reload the page

### Impact
The user is confused

### Possible root cause
Bad UX design

**Comment by Tyratox** [comment]
The goal of the button actually is to connect to multiple servers from the same lao (e.g. multiple organizers, witnesses, ...) so it has the intended functionality. Connecting to multiple LAOs is currently not supported and would require major refactoring.

But I agree that this is not straight-forward to see and not very user-friendly. But since multiple servers are not yet supported by the back-end I think this issue does not have high priority.

**Comment by Tyratox** [comment]
Button was removed during this semester's work
