### ISSUE TITLE
[BUG] Very high cpu usage 

### ISSUE THREAD

**Issue by MeKHell** [dedis/popstellar#1508]
### Description (Actual behavior)
High CPU usage when we have others LAO unprocessed messages.

### How to reproduce
1. Have multiple open LAOS and open one.

### Version & Environment
This bug was reproduced on:
- Commit: 1.9 release
##### Front-ends:
- [x] Fe1-Web (all versions)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

### Impact
Indicate here, based on your understanding, what the possible consequences of this bug are.
[e.g. The app becomes unusable, as data gets permanently corrupted and it crashes on every subsequent start]

### Possible root cause
The Processing of the witness message after the Issue removing warning messages.

**Comment by pierluca** [comment]
@MeKHell has this issue been wholly fixed in #1535 ? 

FYI, if you indicate in a PR something like `fixes #1508` GitHub will automatically close the issue for you.
Here's the list of keywords: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by MeKHell** [comment]
I used the only keyword that I thought was in but did not. :sweat_smile: It is indeed solved.
