### ISSUE TITLE
[BUG] Fe1-Web election end is not implemented correctly

### ISSUE THREAD

**Issue by rjaccard** [dedis/popstellar#703]
### Description (Actual behavior)
We cannot close an election early as there is no close election button.

### Expected behavior
The expected behaviour can be discussed. It can be very convenient to have the possibility to close an election early but the organizer can misuse this possibility to close an election when his/her option is winning.

##### Front-ends:
- [x] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [x] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

### Workaround
Wait the end of the election.

### Impact
There is no big impact, it is just not very convenient.

<img width="1410" alt="Screen Shot 2021-12-26 at 4 11 18 pm" src="https://user-images.githubusercontent.com/61380023/147421429-8655e770-e3d5-4415-b2f2-45afc6b69d23.png">

**Comment by arnauds5** [comment]
Closing an election earlier/later could be done in the future with a consensus between organizer/witnesses to avoid an abuse of organizer where he could choose when to close the election to win.

**Comment by pierluca** [comment]
Currently the implementation is very wrong:
-> after the election end time, the fe1-web updates its _internal state_ , based on the time, without being triggered by a broadcast message, contrary to the global application architecture.
-> when an election is open, there should instead be a button to terminate the election and send the right message [election#end](https://github.com/dedis/popstellar/blob/master/docs/messageData.md#ending-an-election-electionend)

**Comment by Tyratox** [comment]
Currently when sending an [election#end](https://github.com/dedis/popstellar/blob/master/docs/messageData.md#ending-an-election-electionend) message before the end time has passed, the go server replies with

```json
{
  "jsonrpc": "2.0",
  "id": 3,
  "error": {
    "code": -4,
    "description": "failed to handle method: failed to publish: failed to handle a publish message: failed to process \"end\" action: failed to end election: invalid election#end message: election end created at is 1645777760, should be greater or equal to defined end time 1645781233"
  }
}
```

and logs 

```
send error msg="{\"jsonrpc\":\"2.0\",\"id\":3,\"error\":{\"code\":-4,\"description\":\"failed to handle method: failed to publish: failed to handle a publish message: failed to process \\\"end\\\" action: failed to end election: invalid election#end message: election end created at is 1645777760, should be greater or equal to defined end time 1645781233\"}}" role="client socket" to=127.0.0.1:50211
```

The crucial part is "election end created at is 1645777760, should be greater or equal to defined end time 1645781233". Hence it seems as if election closing before the end is not supported by the go backend. (I assume this is the reason `Be1-Go` is also checked in this issue)

When waiting for the election to finish, the message can correctly be sent and the backend accepts it. The backend then calls the function to broadcast the election result (the logs are written to stdout) but until now I was not able to receive this broadcast message on the frontend (not even an "unhandled message type" error or something along these lines was thrown). Is this a known issue? I will keep debugging it in any case and will also try the same functionality with the scala backend as there this might already be implemented.

**Comment by Tyratox** [comment]
In the scala backend the relevant e-voting part is not yet implemented, hence it does not work there either. Thus it seems that for closing an election early, both backends have to implement this functionality before pressing the button "Terminate Election / Tally Votes" before the election time is over will actually work.

@pierluca Regarding
> after the election end time, the fe1-web updates its internal state , based on the time, without being triggered by a broadcast message, contrary to the global application architecture.

I removed the two timers but this now leads to the situation that the UI does not know when to update since the backend does not send a message to the clients notifying them about the election end. When reloading after the time has passed, the election status appears to have updated which means the backend keeps track of the election end. At the same time when the backend updates the election status to finished it could send a broadcast message to the clients informing them about the election status update? (We also want the UI to update when the election was planned for the future and thus it would not suffice to use the [election#result](https://github.com/dedis/popstellar/blob/master/docs/messageData.md#sending-the-results-of-an-election-electionresult) message for this)

It seems that the docs do not yet include a specification for election status update messages but to me it currently seems this might be necessary or does anybody see a better solution?

**Comment by Tyratox** [comment]
For the election end, [election#end](https://github.com/dedis/popstellar/blob/master/docs/messageData.md#ending-an-election-electionend) can be used and for the opening of an election [a PR already existed for adding an election#open message](https://github.com/dedis/popstellar/pull/657). I will incorporate the protocol parts of this into https://github.com/dedis/popstellar/tree/work-fe1-nico but will not add the consensus parts as this is not the focus for this semester. Still, in the end it should then be easier to incorporate the remaining changes of this PR.

**Comment by Tesa27** [comment]
The fix has been addressed and has been merged to master so we can dismiss this issue
